### PR TITLE
Data processing in R

### PR DESCRIPTION
**Pull request by earcanal**

### CODE REVIEW

**Comment by vsoch** [comment]
Cool! So how would I run the tests?

**Comment by vsoch** [comment]
Just by executing the test script? (or does R have it's own "unittest" equivalent?)

**Comment by earcanal** [comment]
It has it's own unit test framework.  You can run them using `Build > Test Package` in RStudio.

**Comment by earcanal** [comment]
`File > Open Project`  ... `efsmsr/efsmsr.Rproj` first.

**Comment by vsoch** [comment]
Yes but we need a version to run in continuous integration :) See if you can figure out how to do that, and please add to the pr! CircleCI works nicely, if you can't turn it on let me know and I can do it.

**Comment by earcanal** [comment]
Looks like it runs `devtools::test()` under the hood.  Hopefully that's enough for CI, otherwise I would read [the gory details](http://r-pkgs.had.co.nz/check.html).

**Comment by vsoch** [comment]
What exactly does the folder "efsmsr" mean? It's not really an intuitive name, tbh.

**Comment by earcanal** [comment]
[Namespaces are a bit of a mess in R](http://r-pkgs.had.co.nz/package.html#naming).  It was the best I could come up with.  The rationale was to start package names with `ef` so they would be easily identifiable (on CRAN).  It might be worth bouncing this round a bit and renaming if we can come up with a better scheme.

**Pull request closed without merging**
