### PR TITLE
Remove "welcome" screen.

### PR DESCRIPTION
**Pull request by earcanal**

### CODE REVIEW

**Comment by vsoch** [comment]
The introduction screen is important to have, because it might be the case that the participant wants to take a break between the tasks (and leave it there). I wasn't the primary person to first argue that it was needed but now I see this use as important, so I disagree that we should remove it.

**Comment by earcanal** [comment]
Feedback from my pilot was that the survey welcome screens were confusing/unnecessary.  You can still take a break without having the welcome page.  If you want to explicitly offer a break, I think it should be done via a different task rather than hard-coded into every survey.

For my use case I can just build using my fork of surveys which don't have the initial screen.  I suspect others will eventually want the option of not having this initial screen though, as it breaks the flow of a study when you don't want to offer a break.

**Comment by earcanal** [comment]
Incidentally, a general "transition" task that displays one or more configurable HTML pages and requires a response would be useful.  I often need this to display "Contact the researcher." messages between tasks in the lab.

**Comment by vsoch** [comment]
@IanEisenberg what are your thoughts here on removing the welcome screens?

**Comment by earcanal** [comment]
For reference, I'm pretty sure I'm the only person who currently uses this survey(!).  The [other PR is for the FFMQ](https://github.com/expfactory-experiments/five-facet-mindfulness-survey/pull/1).

**Comment by vsoch** [comment]
It's been used (in it's previous deployment structure) I believe on Amazon MTurk.

**Comment by earcanal** [comment]
Really?!  Someone found something I made useful?!  I thought this was a bit of an obscure instrument. :)

**Comment by vsoch** [comment]
Haha sorry,  I should be more specific! I meant that the general structure of an experiment or survey having a start page has a rational.

**Comment by vsoch** [comment]
Merge?

**Comment by earcanal** [comment]
I forgot this was a fork of an "official" repo! Yeah, should be good to merge now I've reverted `README.md`.

**Comment by vsoch** [comment]
Well you opened a pull request @earcanal :P

**Review by vsoch — APPROVED** [review]

**Comment by earcanal** [comment]
Hmm, I didn't PR explicitly. I just pushed and deleted an old branch that needed pruning. Magik!

**Pull request merged**
