### PR TITLE
Rename r package

### PR DESCRIPTION
**Pull request by earcanal**

### CODE REVIEW

**Comment by earcanal** [comment]
Finally!

**Comment by vsoch** [comment]
okay here are the issues I see

```
* checking DESCRIPTION meta-information ... WARNING
Non-standard license specification:
  BSD 3-Clause License
```
```
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'process_expfactory_survey'
  ‘flat’
Documented arguments not in \usage in documentation object 'process_expfactory_survey':
  ‘flat=FALSE’
```
and we likely need to ignore these guys

```
checking for hidden files and directories ... NOTE
Found the following hidden files and directories:
  .circleci
These were most likely included in error. See section ‘Package
structure’ in the ‘Writing R Extensions’ manual.

checking top-level files ... NOTE
Non-standard files/directories found at top level:
  ‘CHANGELOG.md’ ‘docker’ ‘Dockerfile’

checking R code for possible problems ... NOTE
process_expfactory_survey: no visible global function definition for
  ‘%>%’
process_expfactory_survey: no visible global function definition for
  ‘stack’
process_expfactory_survey: no visible global function definition for
  ‘rename’
process_expfactory_survey: no visible binding for global variable
  ‘values’
process_expfactory_survey: no visible global function definition for
... 17 lines ...
  ‘Token’
process_expfactory_survey: no visible binding for global variable
  ‘question’
Undefined global functions or variables:
  %>% filter ind key mutate name question rename select spread stack
  text Token value values
Consider adding
  importFrom("graphics", "text")
  importFrom("stats", "filter")
  importFrom("utils", "stack")
to your NAMESPACE file.
```
I think most of these are minor - I just fixed the LICENSE warning and you can take a look at the others later if you want to tweak things. I'm going to merge to test the deployment step, and then take a look at the next repo in the queue!

**Comment by vsoch** [comment]
oups definitely posted that at the wrong one... this should be for expfactoryr :)

**Comment by vsoch** [comment]
too many Github windows open!

**Pull request closed without merging**
